@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

' Main system
System_Boundary(s1, "RecallAI System") {
    Container(webApp, "React Frontend", "React + JavaScript", "User facing web app.")
    Container(api, "Backend API", "C#/.NET", "Handles authentication and business logic.")
    ContainerDb(db, "Postgres Database", "PostgreSQL", "Stores user data, files, chat history and resource usage.")
    ContainerDb(qdrant, "Qdrant Vector DB", "Qdrant", "Stores embeddings for semantic search.")
    ContainerQueue(queue, "RabbitMQ", "Message Broker", "Queues file-related events")
}

' External systems
Person(user, "User", "A registered user of the RecallAI system")
System_Ext(openai, "OPEN AI", "Used for semantic questioning.")

' Relationships
Rel_Right(user, webApp, "Uses")
Rel_Right(webApp, api, "Calls REST APIs")
Rel_Up(api, db, "Reads/Writes data")
Rel_Right(api, queue, "Publishes and consumes file events")
Rel_Up(api, qdrant, "Stores and retrieves embeddings")
Rel_Down(api, openai, "Calls REST APIs")

@enduml
